// NOTE: Assertions have been autogenerated by utils/generate-test-checks.py
// RUN: dynamatic-opt --push-constants --remove-operation-names %s --split-input-file | FileCheck %s
// RUN: dynamatic-opt --push-constants="through-branches" --remove-operation-names %s --split-input-file | FileCheck %s --check-prefix=THROUGH

// CHECK-LABEL:   func.func @doNothing(
// CHECK-SAME:                         %[[VAL_0:.*]]: i32) -> i32 {
// CHECK:           %[[VAL_1:.*]] = arith.constant 10 : i32
// CHECK:           %[[VAL_2:.*]] = arith.cmpi eq, %[[VAL_0]], %[[VAL_1]] : i32
// CHECK:           cf.cond_br %[[VAL_2]], ^bb1, ^bb2
// CHECK:         ^bb1:
// CHECK:           %[[VAL_3:.*]] = arith.constant 1 : i32
// CHECK:           return %[[VAL_3]] : i32
// CHECK:         ^bb2:
// CHECK:           %[[VAL_4:.*]] = arith.constant 0 : i32
// CHECK:           return %[[VAL_4]] : i32
// CHECK:         }
func.func @doNothing(%arg0: i32) -> i32 {
  %c10 = arith.constant 10 : i32
  %eq = arith.cmpi eq, %arg0, %c10 : i32
  cf.cond_br %eq, ^bb1, ^bb2
^bb1:
  %c1 = arith.constant 1 : i32
  return %c1 : i32
^bb2:
  %c0 = arith.constant 0 : i32
  return %c0 : i32
}

// -----

// CHECK-LABEL:   func.func @simplePush(
// CHECK-SAME:                          %[[VAL_0:.*]]: i32) -> i32 {
// CHECK:           %[[VAL_1:.*]] = arith.constant 10 : i32
// CHECK:           %[[VAL_2:.*]] = arith.cmpi eq, %[[VAL_0]], %[[VAL_1]] : i32
// CHECK:           cf.cond_br %[[VAL_2]], ^bb1, ^bb2
// CHECK:         ^bb1:
// CHECK:           %[[VAL_3:.*]] = arith.constant 10 : i32
// CHECK:           return %[[VAL_3]] : i32
// CHECK:         ^bb2:
// CHECK:           %[[VAL_4:.*]] = arith.constant 10 : i32
// CHECK:           %[[VAL_5:.*]] = arith.subi %[[VAL_4]], %[[VAL_4]] : i32
// CHECK:           return %[[VAL_5]] : i32
// CHECK:         }
func.func @simplePush(%arg0: i32) -> i32 {
  %c10 = arith.constant 10 : i32
  %eq = arith.cmpi eq, %arg0, %c10 : i32
  cf.cond_br %eq, ^bb1, ^bb2
^bb1:
  return %c10 : i32
^bb2:
  %sub = arith.subi %c10, %c10 : i32
  return %sub : i32
}

// -----

// CHECK-LABEL:   func.func @pushAndDelete(
// CHECK-SAME:                             %[[VAL_0:.*]]: i1) -> i32 {
// CHECK:           cf.cond_br %[[VAL_0]], ^bb1, ^bb2
// CHECK:         ^bb1:
// CHECK:           %[[VAL_1:.*]] = arith.constant 0 : i32
// CHECK:           return %[[VAL_1]] : i32
// CHECK:         ^bb2:
// CHECK:           %[[VAL_2:.*]] = arith.constant 1 : i32
// CHECK:           return %[[VAL_2]] : i32
// CHECK:         }
func.func @pushAndDelete(%arg0: i1) -> i32 {
  %c0 = arith.constant 0 : i32
  %c1 = arith.constant 1 : i32
  cf.cond_br %arg0, ^bb1, ^bb2
^bb1:
  return %c0 : i32
^bb2:
  return %c1 : i32
}

// -----

// A function nested in another operation's region is processed too: the
// constant defined in the entry block moves to the block that uses it.

// CHECK-LABEL:   func.func @nestedPush(
// CHECK-SAME:                          %[[VAL_0:.*]]: i32) -> i32 {
// CHECK-NOT:       arith.constant
// CHECK:           cf.br ^bb1
// CHECK:         ^bb1:
// CHECK:           %[[VAL_1:.*]] = arith.constant 3 : i32
// CHECK:           %[[VAL_2:.*]] = arith.shrsi %[[VAL_0]], %[[VAL_1]] : i32
// CHECK:           return %[[VAL_2]] : i32
// CHECK:         }
module {
  module @inner {
    func.func @nestedPush(%arg0: i32) -> i32 {
      %c3 = arith.constant 3 : i32
      cf.br ^bb1
    ^bb1:
      %shr = arith.shrsi %arg0, %c3 : i32
      return %shr : i32
    }
  }
}

// -----

// A constant forwarded along one edge of a conditional branch stays on the
// branch without `through-branches`; the option gives that edge a block that
// defines it, and leaves the edge that forwards no constant alone.

// CHECK-LABEL:   func.func @forwardedConstant(
// CHECK:           cf.cond_br %{{.*}}, ^bb1, ^bb2(%[[C0:.*]], %{{.*}} : i32, i32)
// THROUGH-LABEL: func.func @forwardedConstant(
// THROUGH-SAME:    %[[ARG0:.*]]: i1, %[[ARG1:.*]]: i32) -> i32 {
// THROUGH:         cf.cond_br %[[ARG0]], ^bb1, ^bb2
// THROUGH:       ^bb1:
// THROUGH:         %[[ADD:.*]] = arith.addi %[[ARG1]], %[[ARG1]] : i32
// THROUGH:         cf.br ^bb3(%[[ADD]], %[[ARG1]] : i32, i32)
// THROUGH:       ^bb2:
// THROUGH:         %[[C0:.*]] = arith.constant 0 : i32
// THROUGH:         cf.br ^bb3(%[[C0]], %[[ARG1]] : i32, i32)
// THROUGH:       ^bb3(%[[X:.*]]: i32, %[[Y:.*]]: i32):
// THROUGH:         %[[SUM:.*]] = arith.addi %[[X]], %[[Y]] : i32
// THROUGH:         return %[[SUM]] : i32
// THROUGH:       }
func.func @forwardedConstant(%arg0: i1, %arg1: i32) -> i32 {
  %c0 = arith.constant 0 : i32
  cf.cond_br %arg0, ^bb1, ^bb2(%c0, %arg1 : i32, i32)
^bb1:
  %add = arith.addi %arg1, %arg1 : i32
  cf.br ^bb2(%add, %arg1 : i32, i32)
^bb2(%x: i32, %y: i32):
  %sum = arith.addi %x, %y : i32
  return %sum : i32
}
